if(EXISTS "/home/tony/Development/personal/vigilant-canine/tests/storage/database_test[1]_tests.cmake")
  include("/home/tony/Development/personal/vigilant-canine/tests/storage/database_test[1]_tests.cmake")
else()
  add_test(database_test_NOT_BUILT database_test_NOT_BUILT)
endif()
