if(EXISTS "/home/tony/Development/personal/vigilant-canine/tests/distro/detector_test[1]_tests.cmake")
  include("/home/tony/Development/personal/vigilant-canine/tests/distro/detector_test[1]_tests.cmake")
else()
  add_test(detector_test_NOT_BUILT detector_test_NOT_BUILT)
endif()
