add_test([=[HashTest.Blake3EmptyString]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.Blake3EmptyString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.Blake3EmptyString]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.Blake3HelloWorld]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.Blake3HelloWorld]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.Blake3HelloWorld]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.Sha256EmptyString]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.Sha256EmptyString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.Sha256EmptyString]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.Sha256HelloWorld]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.Sha256HelloWorld]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.Sha256HelloWorld]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.HashFileSuccess]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.HashFileSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.HashFileSuccess]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.HashFileNotFound]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.HashFileNotFound]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.HashFileNotFound]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.AlgorithmToString]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.AlgorithmToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.AlgorithmToString]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HashTest.StringToAlgorithm]=]  /home/tony/Development/personal/vigilant-canine/tests/core/hash_test [==[--gtest_filter=HashTest.StringToAlgorithm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HashTest.StringToAlgorithm]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/core SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  hash_test_TESTS HashTest.Blake3EmptyString HashTest.Blake3HelloWorld HashTest.Sha256EmptyString HashTest.Sha256HelloWorld HashTest.HashFileSuccess HashTest.HashFileNotFound HashTest.AlgorithmToString HashTest.StringToAlgorithm)
