if(EXISTS "/home/tony/Development/personal/vigilant-canine/tests/scanner/scanner_test[1]_tests.cmake")
  include("/home/tony/Development/personal/vigilant-canine/tests/scanner/scanner_test[1]_tests.cmake")
else()
  add_test(scanner_test_NOT_BUILT scanner_test_NOT_BUILT)
endif()
