if(EXISTS "/home/tony/Development/personal/vigilant-canine/tests/config/config_test[1]_tests.cmake")
  include("/home/tony/Development/personal/vigilant-canine/tests/config/config_test[1]_tests.cmake")
else()
  add_test(config_test_NOT_BUILT config_test_NOT_BUILT)
endif()
