add_test([=[ConfigTest.LoadDefaultConfig]=]  /home/tony/Development/personal/vigilant-canine/tests/config/config_test [==[--gtest_filter=ConfigTest.LoadDefaultConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConfigTest.LoadDefaultConfig]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/config SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConfigTest.LoadValidConfig]=]  /home/tony/Development/personal/vigilant-canine/tests/config/config_test [==[--gtest_filter=ConfigTest.LoadValidConfig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConfigTest.LoadValidConfig]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/config SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConfigTest.InvalidTomlSyntax]=]  /home/tony/Development/personal/vigilant-canine/tests/config/config_test [==[--gtest_filter=ConfigTest.InvalidTomlSyntax]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConfigTest.InvalidTomlSyntax]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/config SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ConfigTest.InvalidHashAlgorithm]=]  /home/tony/Development/personal/vigilant-canine/tests/config/config_test [==[--gtest_filter=ConfigTest.InvalidHashAlgorithm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ConfigTest.InvalidHashAlgorithm]=]  PROPERTIES WORKING_DIRECTORY /home/tony/Development/personal/vigilant-canine/tests/config SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  config_test_TESTS ConfigTest.LoadDefaultConfig ConfigTest.LoadValidConfig ConfigTest.InvalidTomlSyntax ConfigTest.InvalidHashAlgorithm)
